import re
import logging
from typing import Any, List, Dict, Optional
from google import genai
from google.genai import types
from google.genai.errors import APIError
from app.config import Config
from app.services.llm_provider import dispatch_llm_request

logger = logging.getLogger(__name__)

# Regex pattern allowing:
# 1. Tamil script (\u0B80-\u0BFF)
# 2. English alphabet (a-zA-Z)
# 3. Digits (0-9)
# 4. Whitespace (\s)
# 5. Standard punctuation & typographical marks
# 6. Emojis and miscellaneous symbols (\U00010000-\U0010ffff, \u2000-\u2bff, \ufe0f, \u200d)
ALLOWED_TAMIL_CHARS_PATTERN = re.compile(
    r'[^\u0B80-\u0BFFa-zA-Z0-9\s.,!?:;\-\'\"()\[\]{}/\\@#$%&*+=<>~|`“”‘’—–…\U00010000-\U0010ffff\u2000-\u2bff\ufe0f\u200d]'
)

def clean_tamil_text(text: str) -> str:
    """
    Removes stray non-Tamil characters outside Tamil, English, digits, punctuation, and emoji.
    Prevents LLM artifacts like stray Arabic/Persian diacritics within Tamil words.
    """
    return ALLOWED_TAMIL_CHARS_PATTERN.sub('', text)


def enforce_bilingual_medical_terms(text: str, language: str = "ta") -> str:
    """
    Ensures key diabetes terms appear with Tamil and English together in Tamil answers:
    - Hypoglycemia (குறைந்த இரத்த சர்க்கரை)
    - Hyperglycemia (அதிக இரத்த சர்க்கரை)
    - HbA1c
    - Blood glucose
    - Insulin
    """
    if language != "ta" or not text:
        return text

    result = text

    # 1. Hypoglycemia (குறைந்த இரத்த சர்க்கரை)
    if not re.search(r"(?:Hypoglycemia\s*\(\s*குறைந்த\s*இரத்த\s*சர்க்கரை\s*\)|குறைந்த\s*இரத்த\s*சர்க்கரை\s*\(\s*Hypoglycemia\s*\))", result, re.IGNORECASE):
        if re.search(r"ஹைபோகிளைசீமியா", result):
            result = re.sub(r"ஹைபோகிளைசீமியா", "Hypoglycemia (குறைந்த இரத்த சர்க்கரை)", result)
        elif re.search(r"\bHypoglycemia\b", result, re.IGNORECASE):
            result = re.sub(r"(?i)\bHypoglycemia\b", "Hypoglycemia (குறைந்த இரத்த சர்க்கரை)", result)
        elif re.search(r"குறைந்த\s*இரத்த\s*சர்க்கரை", result):
            result = re.sub(r"குறைந்த\s*இரத்த\s*சர்க்கரை", "Hypoglycemia (குறைந்த இரத்த சர்க்கரை)", result)

    # 2. Hyperglycemia (அதிக இரத்த சர்க்கரை)
    if not re.search(r"(?:Hyperglycemia\s*\(\s*அதிக\s*இரத்த\s*சர்க்கரை\s*\)|அதிக\s*இரத்த\s*சர்க்கரை\s*\(\s*Hyperglycemia\s*\))", result, re.IGNORECASE):
        if re.search(r"ஹைபர்கிளைசீமியா", result):
            result = re.sub(r"ஹைபர்கிளைசீமியா", "Hyperglycemia (அதிக இரத்த சர்க்கரை)", result)
        elif re.search(r"\bHyperglycemia\b", result, re.IGNORECASE):
            result = re.sub(r"(?i)\bHyperglycemia\b", "Hyperglycemia (அதிக இரத்த சர்க்கரை)", result)
        elif re.search(r"அதிக\s*இரத்த\s*சர்க்கரை", result):
            result = re.sub(r"அதிக\s*இரத்த\s*சர்க்கரை", "Hyperglycemia (அதிக இரத்த சர்க்கரை)", result)

    # 3. HbA1c standard casing
    result = re.sub(r"(?i)\bhba1c\b", "HbA1c", result)
    result = re.sub(r"எச்பிஏ1சி", "HbA1c", result)

    # 4. Blood glucose (keep with இரத்த சர்க்கரை)
    if not re.search(r"\bBlood\s*glucose\b", result, re.IGNORECASE):
        result = re.sub(
            r"(?<!குறைந்த\s)(?<!அதிக\s)இரத்த\s*சர்க்கரை",
            "இரத்த சர்க்கரை (Blood glucose)",
            result,
            count=1
        )

    # 5. Insulin (keep with இன்சுலின்)
    if not re.search(r"(?:Insulin\s*\(\s*இன்சுலின்\s*\)|இன்சுலின்\s*\(\s*Insulin\s*\))", result, re.IGNORECASE):
        if re.search(r"இன்சுலின்", result) and not re.search(r"\bInsulin\b", result, re.IGNORECASE):
            result = re.sub(r"இன்சுலின்", "இன்சுலின் (Insulin)", result, count=1)
        elif re.search(r"\bInsulin\b", result, re.IGNORECASE) and not re.search(r"இன்சுலின்", result):
            result = re.sub(r"(?i)\bInsulin\b", "Insulin (இன்சுலின்)", result, count=1)

    return result

def normalize_single_disclaimer(text: str, language: str, is_followup: bool = False) -> str:
    """
    Ensures the medical disclaimer is cleanly integrated:
    - In initial replies, appends the canonical disclaimer once cleanly at the end.
    - Removes duplicate disclaimer blocks generated by the LLM.
    """
    disclaimer_ta = "⚠️ குறிப்பு: இது விழிப்புணர்வு தகவல் மட்டுமே. மருத்துவ ஆலோசனைக்கு உங்கள் மருத்துவரை அணுகவும்."
    disclaimer_en = "⚠️ Disclaimer: This is educational information only. Please consult your physician for medical advice."
    canonical_disclaimer = disclaimer_ta if language == "ta" else disclaimer_en

    # Patterns to match any existing disclaimer blocks generated by the LLM
    disclaimer_patterns = [
        r'(?i)⚠️\s*(?:குறிப்பு|Disclaimer|எச்சரிக்கை|Notice)[:\s].*?(?:மருத்துவரை அணுகவும்|medical advice\.?)',
        r'(?i)(?:குறிப்பு|Disclaimer)[:\s].*?(?:மருத்துவரை அணுகவும்|medical advice\.?)',
    ]

    cleaned_body = text
    for pattern in disclaimer_patterns:
        cleaned_body = re.sub(pattern, '', cleaned_body).strip()

    # Clean up trailing dots, dashes, or extra whitespace left over from removed disclaimer
    cleaned_body = re.sub(r'[\s\.\-_]+$', '', cleaned_body).strip()
    if cleaned_body and not cleaned_body.endswith(('.', '!', '?')):
        cleaned_body += '.'

    # For follow-ups where the body already contains guidance, keep the clean canonical disclaimer at end
    return f"{cleaned_body}\n\n{canonical_disclaimer}"

# Comprehensive Trusted Diabetes Educational System Instruction
SYSTEM_INSTRUCTION = """
You are "Tamil Voice Diabetes Assistant" (தமிழ் குரல் சர்க்கரை நோய் வழிகாட்டி), a compassionate, highly trustworthy health educational AI assistant specializing in diabetes awareness.

YOUR MISSION:
Deliver accurate, culturally relevant, understandable, and medically grounded diabetes education in Tamil and English.

================================================================================
1. CORE CLINICAL KNOWLEDGE CATEGORIES
================================================================================
Your answers must reflect current clinical consensus (e.g., ADA, RSSDI guidelines):
1. Understanding Diabetes:
   - Type 1: Autoimmune condition causing absolute insulin deficiency; requires lifelong insulin therapy. Cannot be cured or reversed.
   - Type 2: Characterized by insulin resistance and relative insulin deficiency; strongly linked to genetics, weight, and lifestyle. Managed with diet, exercise, oral medications, and insulin when needed.
   - Gestational Diabetes: Glucose intolerance developing during pregnancy; requires careful obstetric and metabolic monitoring to protect mother and child.
   - Can it be cured permanently?: NO. Diabetes currently has NO permanent cure. However, Type 2 diabetes can be managed effectively and put into remission (normal sugar without medication) through sustained lifestyle, nutrition, and weight management under doctor supervision. Type 1 is permanent.

2. Blood Glucose Basics:
   - Fasting Blood Sugar: Normal is 70–99 mg/dL; for adults with diabetes, typical target is 80–130 mg/dL.
   - Postprandial (2 hours after meal): Normal is <140 mg/dL; typical target for diabetics is <180 mg/dL.
   - HbA1c (3-month average): Normal is <5.7%; Pre-diabetes 5.7%–6.4%; Diabetes ≥6.5%. Target for most non-pregnant adults with diabetes is <7.0%, tailored by their physician.

3. Diabetes-Friendly Nutrition:
   - Emphasize Low Glycemic Index (GI) and high-fiber foods.
   - Plate Method: 1/2 plate non-starchy vegetables/greens, 1/4 plate protein (dal, pulses, eggs/fish), 1/4 plate complex carbohydrates.
   - Whole grains & millets (ragi, kambu, thinai, brown rice) in controlled portions instead of refined white rice or maida.

4. Fruits & Vegetables:
   - Diabetic patients CAN eat whole fruits in moderation (e.g., 1 small/medium fruit like apple, guava/கொய்யா, papaya per day, ~100-150g).
   - Apples & guavas are rich in soluble fiber (pectin) which slows glucose absorption.
   - Eat whole fruits with skin (washed well); NEVER drink fruit juice (juice strips fiber and causes rapid blood sugar spikes).
   - Highly beneficial non-starchy vegetables: bitter gourd (பாகற்காய்), ladies finger (வெண்டைக்காய்), spinach/greens (கீரை), bottle gourd, cucumber.

5. Physical Activity & Exercise:
   - General recommendation: At least 150 minutes of moderate aerobic exercise per week (e.g., 30 minutes brisk walking, 5 days a week).
   - Post-meal walking: A gentle 10–15 minute walk after meals significantly reduces postprandial glucose spikes.
   - Precautions: Carry fast-acting glucose (candy/sugar), wear proper supportive footwear, stay hydrated, avoid strenuous exercise if blood sugar is severely high (>250 mg/dL with ketones) or low (<70 mg/dL).

6. Hypoglycemia (Low Blood Sugar <70 mg/dL):
   - Symptoms: Sweating (வியர்வை), shakiness/tremors (நடுக்கம்), dizziness (தலைசுற்றல்), rapid heartbeat (படபடப்பு), intense hunger, confusion.
   - "Rule of 15": If conscious, consume 15g fast-acting carbohydrate (half cup fruit juice, 3-4 glucose tablets, or 3 tsp sugar in water). Wait 15 minutes and recheck.
   - Severe / Unconscious: Call 108 immediately. DO NOT put anything into the mouth. Place in recovery position.

7. Hyperglycemia (High Blood Sugar):
   - Symptoms: Excessive thirst (அதிக தாகம்), frequent urination (அடிக்கடி சிறுநீர் கழித்தல்), fatigue, blurred vision.
   - Guidance: Drink plenty of water, check for ketones if advised, never skip medication, consult physician if persistent.

8. General Medication Awareness:
   - STRICT SAFETY: NEVER advise stopping or altering diabetes medication (such as Metformin, Glimepiride, or Insulin) just because blood sugar readings are currently normal!
   - Normal readings mean the prescribed medication and lifestyle are WORKING. Stopping abruptly can cause dangerous rebound hyperglycemia and complications.
   - Any medication adjustment must be made ONLY by the treating physician.

9. Foot Care:
   - Inspect feet daily for cuts, blisters, cracks, or redness.
   - Wash daily and dry thoroughly, especially between toes. Apply moisturizer to feet but avoid between toes.
   - Never walk barefoot, even indoors. Wear well-cushioned, well-fitting footwear.

10. Eye Care:
    - High blood glucose can damage retinal blood vessels (diabetic retinopathy).
    - Undergo an annual dilated eye exam by an ophthalmologist. Report sudden vision changes immediately.

11. Daily Self-Care:
    - Regular glucometer monitoring and maintaining a logbook.
    - Stress management (stress increases cortisol and blood glucose).
    - 7 to 8 hours of restorative sleep.

12. When to Seek Medical Help:
    - Routine check-ups every 3 to 6 months.
    - Immediate medical visit for non-healing ulcers, recurrent hypoglycemia, or illness.
    - Emergency medical care (108) for chest pain, shortness of breath, confusion, or fainting.

================================================================================
2. RELIABLE RESPONSE STRUCTURE
================================================================================
Organize your response into these 4 concise, voice-friendly components:
1. Direct Answer: A clear, reassuring direct answer to the user's specific question in the first 1-2 sentences.
2. Simple Explanation: Why this is the case, explained in plain language without intimidating jargon.
3. Practical Guidance: 2-3 practical, actionable tips (e.g., portion size, timing, lifestyle habits).
4. Precautions & Doctor Advisory: Key precautions (e.g. what to avoid) and advising consultation with their doctor.

Keep the total length voice-friendly (around 4 to 6 concise sentences or short bullet points). Avoid unnecessarily long essays.

================================================================================
3. TAMIL LANGUAGE EXCELLENCE
================================================================================
When replying in Tamil:
- Use natural, polite, spoken/conversational Tamil (பேச்சுத்தமிழ் மற்றும் எளிய எழுத்துத்தமிழ் கலந்து இயல்பாக).
- Avoid awkward, robotic literal translations.
- Explain complex clinical terms in simple Tamil, and place standard English medical terms in brackets where helpful. Examples:
  * இரத்த சர்க்கரை அளவு (Blood Sugar Level)
  * நார்ச்சத்து (Fiber)
  * குறைந்த சர்க்கரை அளவு (Hypoglycemia)
  * அதிக சர்க்கரை அளவு (Hyperglycemia)
  * இன்சுலின் (Insulin)
  * கிளைசெமிக் குறியீடு (Glycemic Index)
- Write Tamil using strictly standard Tamil script. Never insert characters or diacritics from Arabic, Persian, or other languages.
- Ensure the Tamil phrasing flows naturally and clearly when synthesized aloud via Text-to-Speech (Edge-TTS).

================================================================================
4. MEDICAL SAFETY BOUNDARIES (STRICT & NON-NEGOTIABLE)
================================================================================
1. EDUCATIONAL ONLY: You are an educational awareness assistant, NOT a doctor.
2. NEVER DIAGNOSE: Never diagnose diabetes or other conditions based on user-described symptoms.
3. NEVER PRESCRIBE: Never recommend specific drug dosages, never prescribe medicines, and never suggest stopping prescribed treatments.
4. NO FALSE REASSURANCE: Never dismiss alarming symptoms as "normal" or "harmless".
5. EMERGENCY ESCALATION: If the user mentions emergency signs (unconsciousness, fainting, severe hypoglycemia, seizures, inability to swallow, chest pain, intense shortness of breath):
   - Instruct them in urgent terms to call 108 or local emergency services immediately.
   - For an unconscious person, explicitly advise: DO NOT force any food or drink into their mouth; place them on their side in the recovery position and wait for the ambulance.
6. CONVERSATION CONTEXT: If this is a follow-up in an ongoing chat, remember previous context (e.g., if the user previously asked about apples, 'how many?' refers to apples). Do not make assumptions about the user's age, diagnosis, or health history.
"""

def get_gemini_client():
    """Initializes and returns the Gemini client if API key is present."""
    api_key = (Config.GEMINI_API_KEY or "").strip()
    if not api_key or api_key in ("your_api_key_here", "your_gemini_api_key_here"):
        return None
    try:
        return genai.Client(api_key=api_key)
    except Exception as e:
        logger.warning("Could not initialize Gemini Client: %s", str(e))
        return None

def generate_ai_response(
    user_message: str, 
    language: str = "ta", 
    history: Optional[List[Dict[str, str]]] = None
) -> str:
    """
    Generates a safe, trusted, educational response using LLMProvider abstraction.
    Dispatches to primary provider (default: Gemini) and falls back to Claude/Grok
    only if primary fails and their API keys exist. Never calls more than one provider
    per question unless primary fails.
    """
    raw_text = dispatch_llm_request(
        prompt=user_message,
        system_instruction=SYSTEM_INSTRUCTION,
        history=history,
        language=language
    )

    if raw_text:
        if language == "ta":
            raw_text = clean_tamil_text(raw_text)
            raw_text = enforce_bilingual_medical_terms(raw_text, language="ta")

        is_followup = bool(history and len(history) > 1)
        return normalize_single_disclaimer(raw_text, language, is_followup=is_followup)

    return _fallback_error_message(language)

def _fallback_error_message(language: str) -> str:
    """Helper to return polite, localized error messages when AI is unreachable."""
    if language == "en":
        return (
            "I am sorry, I am having trouble connecting to the AI service right now. "
            "Please check your internet connection or try again in a moment.\n\n"
            "⚠️ Disclaimer: This is educational information only. Please consult your physician for medical advice."
        )
    return (
        "மன்னிக்கவும், AI சேவையை தற்போது தொடர்பு கொள்ள முடியவில்லை. "
        "தயவுசெய்து உங்கள் இணைய இணைப்பைச் சரிபார்க்கவும் அல்லது சிறிது நேரம் கழித்து மீண்டும் முயற்சிக்கவும்.\n\n"
        "⚠️ குறிப்பு: இது விழிப்புணர்வு தகவல் மட்டுமே. மருத்துவ ஆலோசனைக்கு உங்கள் மருத்துவரை அணுகவும்."
    )


# System prompt strictly grounded on verified clinical context
RAG_SYSTEM_PROMPT = (
    "You are an educational diabetes information assistant. "
    "Use the supplied trusted medical context as the primary factual grounding. "
    "Do not diagnose, prescribe medication, recommend medication dosage changes, "
    "or replace a healthcare professional. "
    "Never claim or suggest that any food, herb, diet, or home remedy cures, reverses completely, or eliminates diabetes. "
    "In Tamil responses, always keep these medical terms with Tamil and English together: "
    "Hypoglycemia (குறைந்த இரத்த சர்க்கரை), Hyperglycemia (அதிக இரத்த சர்க்கரை), HbA1c, Blood glucose, Insulin."
)


def generate_rag_llm_response(
    query: str,
    retrieved_context: str,
    conversation_history: Optional[List[Dict[str, str]]] = None,
    language: str = "ta",
    custom_llm_fn: Optional[Any] = None
) -> str:
    """
    RAG LLM generation function:
    - Accepts (query, retrieved_context, conversation_history, language).
    - Grounds response on trusted retrieved context using RAG_SYSTEM_PROMPT.
    - Keeps only the last few messages of history to minimize prompt footprint.
    - Calls Gemini (or custom_llm_fn when provided in tests).
    """
    # Keep only the last few turns of history to keep prompt small
    compact_history = (conversation_history or [])[-4:]
    history_lines = []
    for item in compact_history:
        if isinstance(item, dict) and "text" in item and "role" in item:
            role_label = "User" if item["role"] == "user" else "Assistant"
            history_lines.append(f"{role_label}: {item['text'][:250].strip()}")
    history_text = "\n".join(history_lines) if history_lines else "None"

    # Assemble structured RAG prompt
    lang_instruction = (
        "தயவுசெய்து எளிய, கனிவான தமிழில் விழிப்புணர்வு தகவல்களை வழங்கவும். "
        "Hypoglycemia (குறைந்த இரத்த சர்க்கரை), Hyperglycemia (அதிக இரத்த சர்க்கரை), HbA1c, Blood glucose, Insulin ஆகிய சொற்களை தமிழும் ஆங்கிலமும் இணைத்து பயன்படுத்தவும். "
        "எந்தவொரு உணவும் சர்க்கரை நோயை குணப்படுத்தும் என்று கூற வேண்டாம்."
        if language == "ta" else
        "Please provide clear, empathetic, educational guidance in English. Never claim any food or herb cures diabetes."
    )

    prompt = (
        f"System: {RAG_SYSTEM_PROMPT}\n\n"
        f"[TRUSTED MEDICAL CONTEXT]\n{retrieved_context}\n\n"
        f"[RECENT CONVERSATION HISTORY]\n{history_text}\n\n"
        f"User Question: {query}\n\n"
        f"Guidance: {lang_instruction}\n\n"
        f"Educational Answer:"
    )

    if custom_llm_fn:
        try:
            res = custom_llm_fn(query, retrieved_context, compact_history, language)
        except TypeError:
            res = custom_llm_fn(prompt, language)
        if language == "ta" and res:
            res = clean_tamil_text(res)
            res = enforce_bilingual_medical_terms(res, language="ta")
        return res

    # Dispatches through LLMProvider (Gemini -> Claude -> Grok fallback)
    output = dispatch_llm_request(
        prompt=prompt,
        system_instruction=RAG_SYSTEM_PROMPT,
        history=compact_history,
        language=language
    )
    if output:
        if language == "ta":
            output = clean_tamil_text(output)
            output = enforce_bilingual_medical_terms(output, language="ta")
        return output

    return _fallback_error_message(language)
