import re
import logging
from google import genai
from google.genai import types
from google.genai.errors import APIError
from config import Config

logger = logging.getLogger(__name__)

# Regex pattern allowing:
# 1. Tamil script (\u0B80-\u0BFF)
# 2. English alphabet (a-zA-Z)
# 3. Digits (0-9)
# 4. Whitespace (\s)
# 5. Standard punctuation & typographical marks
# 6. Emojis and miscellaneous symbols (\U00010000-\U0010ffff, \u2000-\u2bff, \ufe0f, \u200d)
ALLOWED_TAMIL_CHARS_PATTERN = re.compile(
    r'[^\u0B80-\u0BFFa-zA-Z0-9\s.,!?:;\-\'\"()\[\]{}/\\@#$%&*+=<>~|`“”‘’—–…\U00010000-\U0010ffff\u2000-\u2bff\ufe0f\u200d]'
)

def clean_tamil_text(text: str) -> str:
    """
    Removes stray non-Tamil characters outside Tamil, English, digits, punctuation, and emoji.
    Prevents LLM artifacts like stray Arabic/Persian diacritics within Tamil words.
    """
    return ALLOWED_TAMIL_CHARS_PATTERN.sub('', text)

def normalize_single_disclaimer(text: str, language: str) -> str:
    """
    Ensures the medical disclaimer is shown strictly once per reply at the end,
    preventing duplicate disclaimers inside the reply or as separate bubbles.
    """
    disclaimer_ta = "⚠️ குறிப்பு: இது விழிப்புணர்வு தகவல் மட்டுமே. மருத்துவ ஆலோசனைக்கு உங்கள் மருத்துவரை அணுகவும்."
    disclaimer_en = "⚠️ Disclaimer: This is educational information only. Please consult your physician for medical advice."
    canonical_disclaimer = disclaimer_ta if language == "ta" else disclaimer_en

    # Patterns to match any existing disclaimer blocks generated by the LLM
    disclaimer_patterns = [
        r'(?i)⚠️\s*(?:குறிப்பு|Disclaimer|எச்சரிக்கை|Notice)[:\s].*?(?:மருத்துவரை அணுகவும்|medical advice\.?)',
        r'(?i)(?:குறிப்பு|Disclaimer)[:\s].*?(?:மருத்துவரை அணுகவும்|medical advice\.?)',
    ]

    cleaned_body = text
    for pattern in disclaimer_patterns:
        cleaned_body = re.sub(pattern, '', cleaned_body).strip()

    # Clean up trailing dots, dashes, or extra whitespace left over from removed disclaimer
    cleaned_body = re.sub(r'[\s\.\-_]+$', '', cleaned_body).strip()
    if cleaned_body and not cleaned_body.endswith(('.', '!', '?')):
        cleaned_body += '.'

    # Append the canonical disclaimer once cleanly
    return f"{cleaned_body}\n\n{canonical_disclaimer}"

# System instructions enforcing strict medical safety rules & bilingual capability
SYSTEM_INSTRUCTION = """
You are "Tamil Voice Diabetes Assistant" (தமிழ் குரல் சர்க்கரை நோய் வழிகாட்டி), a compassionate and knowledgeable health educational AI assistant.

YOUR MISSION:
Provide general educational information, dietary guidance, physical activity tips, and lifestyle awareness regarding diabetes to users in Tamil and English.

LANGUAGE RULES:
1. Detect and reply in the same language as the user's query:
   - If the user asks in Tamil or Tanglish, reply in clear, conversational, natural Tamil.
   - If the user asks in English, reply in simple, accessible English.
   - If mixed, reply primarily in Tamil with standard English medical terms in brackets if helpful.
2. Write Tamil using only standard Tamil script. Never insert characters, diacritics, or letters from Arabic, Persian, or other non-Tamil languages.
3. Keep replies conversational, concise, and easy to understand aloud (since the reply will be read aloud via Text-to-Speech). Avoid unnecessarily long bullet lists.

RESPONSE LENGTH & COMPLETION RULES (STRICT):
1. Keep the educational explanation concise and voice-friendly: approximately 4 to 6 sentences total.
2. ALWAYS complete your thoughts and sentences. Never stop or cut off mid-sentence.
3. Include the medical disclaimer only once at the end of the reply. Do not repeat the disclaimer inside the body or multiple times.

CRITICAL SAFETY & MEDICAL BOUNDARIES (NON-NEGOTIABLE):
1. EDUCATIONAL ONLY: You provide general health and lifestyle awareness ONLY.
2. NEVER DIAGNOSE: Never attempt to diagnose diabetes or any medical condition based on symptoms described.
3. NEVER PRESCRIBE: Never recommend specific medicines (e.g., Metformin, Insulin), never suggest drug dosages, and never advise stopping or changing prescribed medications.
4. DOCTOR CONSULTATION: Always advise the user to consult their licensed doctor or diabetologist for personal diagnosis and treatment decisions.
5. EMERGENCY PROTOCOL: If the user mentions emergency signs (e.g., severe hypoglycemia/hyperglycemia, intense dizziness, confusion, fainting, shortness of breath, loss of consciousness, chest pain):
   - Immediately instruct them in urgent terms to contact local emergency medical services (e.g., 108) or go to the nearest hospital immediately.
   - For suspected severe low sugar where the person is conscious, mention consuming 15-20g of fast-acting glucose while immediately seeking emergency medical help.

MANDATORY CLOSING DISCLAIMER:
End every non-emergency response with this short disclaimer exactly once:
- In Tamil: "⚠️ குறிப்பு: இது விழிப்புணர்வு தகவல் மட்டுமே. மருத்துவ ஆலோசனைக்கு உங்கள் மருத்துவரை அணுகவும்."
- In English: "⚠️ Disclaimer: This is educational information only. Please consult your physician for medical advice."
"""

def get_gemini_client():
    """Initializes and returns the Gemini client if API key is present."""
    api_key = Config.GEMINI_API_KEY
    if not api_key or api_key == "your_api_key_here":
        return None
    return genai.Client(api_key=api_key)

def generate_ai_response(user_message: str, language: str = "ta") -> str:
    """
    Generates a safe, educational response from Google Gemini.
    Cleans stray script artifacts and ensures exactly one disclaimer per reply.
    """
    client = get_gemini_client()

    # Fallback if API key has not been configured in .env yet
    if not client:
        logger.warning("GEMINI_API_KEY is not set or is still the default placeholder.")
        if language == "en":
            return (
                "⚠️ Notice: Gemini API Key is not configured yet. "
                "Please add your free GEMINI_API_KEY in the .env file to enable live AI responses.\n\n"
                "⚠️ Disclaimer: This is educational information only. Please consult your physician for medical advice."
            )
        return (
            "⚠️ குறிப்பு: Gemini API Key இன்னும் அமைக்கப்படவில்லை. "
            "நேரடி AI பதில்களைப் பெற உங்கள் .env கோப்பில் GEMINI_API_KEY-ஐச் சேர்க்கவும்.\n\n"
            "⚠️ குறிப்பு: இது விழிப்புணர்வு தகவல் மட்டுமே. மருத்துவ ஆலோசனைக்கு உங்கள் மருத்துவரை அணுகவும்."
        )

    # Candidate models in priority order for high availability
    primary_model = Config.GEMINI_MODEL or "gemini-3.5-flash"
    candidate_models = [primary_model, "gemini-3.5-flash", "gemini-3.5-flash-lite", "gemini-3.8-flash"]
    # Deduplicate while preserving order
    candidate_models = list(dict.fromkeys(candidate_models))

    config = types.GenerateContentConfig(
        system_instruction=SYSTEM_INSTRUCTION,
        temperature=0.7,
    )

    last_error = None
    for model_name in candidate_models:
        try:
            logger.info("Calling Gemini model [%s] for user query...", model_name)
            response = client.models.generate_content(
                model=model_name,
                contents=user_message,
                config=config
            )

            if response and response.text:
                raw_text = response.text.strip()

                # Step 1: Clean stray characters outside standard Tamil, English, digits, punctuation, emoji
                if language == "ta":
                    raw_text = clean_tamil_text(raw_text)

                # Step 2: Ensure the medical disclaimer appears strictly once per reply
                final_text = normalize_single_disclaimer(raw_text, language)
                return final_text
            else:
                logger.warning("Model %s returned empty response.", model_name)
                continue

        except APIError as api_err:
            last_error = api_err
            logger.warning("Gemini API Error (%s) on model %s: %s", api_err.code, model_name, api_err.message)
            if api_err.code in (404, 429, 503):
                continue
            return _fallback_error_message(language)

        except Exception as e:
            last_error = e
            logger.error("Unexpected error with model %s: %s", model_name, str(e))
            continue

    # If all candidate models failed
    logger.error("All Gemini model candidates failed. Last error: %s", str(last_error))
    if isinstance(last_error, APIError) and last_error.code == 429:
        if language == "en":
            return (
                "⏳ The AI service is currently busy (rate limit reached). "
                "Please wait a minute and try again.\n\n"
                "⚠️ Disclaimer: This is educational information only. Please consult your physician for medical advice."
            )
        return (
            "⏳ AI சேவை தற்போது மிகவும் பிஸியாக உள்ளது (Rate limit). "
            "தயவுசெய்து ஒரு நிமிடம் கழித்து மீண்டும் முயற்சிக்கவும்.\n\n"
            "⚠️ குறிப்பு: இது விழிப்புணர்வு தகவல் மட்டுமே. மருத்துவ ஆலோசனைக்கு உங்கள் மருத்துவரை அணுகவும்."
        )

    return _fallback_error_message(language)

def _fallback_error_message(language: str) -> str:
    """Helper to return polite, localized error messages when AI is unreachable."""
    if language == "en":
        return (
            "I am sorry, I am having trouble connecting to the AI service right now. "
            "Please check your internet connection or try again in a moment.\n\n"
            "⚠️ Disclaimer: This is educational information only. Please consult your physician for medical advice."
        )
    return (
        "மன்னிக்கவும், AI சேவையை தற்போது தொடர்பு கொள்ள முடியவில்லை. "
        "தயவுசெய்து உங்கள் இணைய இணைப்பைச் சரிபார்க்கவும் அல்லது சிறிது நேரம் கழித்து மீண்டும் முயற்சிக்கவும்.\n\n"
        "⚠️ குறிப்பு: இது விழிப்புணர்வு தகவல் மட்டுமே. மருத்துவ ஆலோசனைக்கு உங்கள் மருத்துவரை அணுகவும்."
    )
