import re
import logging
from typing import List, Dict, Optional
from google import genai
from google.genai import types
from google.genai.errors import APIError
from config import Config

logger = logging.getLogger(__name__)

# Regex pattern allowing:
# 1. Tamil script (\u0B80-\u0BFF)
# 2. English alphabet (a-zA-Z)
# 3. Digits (0-9)
# 4. Whitespace (\s)
# 5. Standard punctuation & typographical marks
# 6. Emojis and miscellaneous symbols (\U00010000-\U0010ffff, \u2000-\u2bff, \ufe0f, \u200d)
ALLOWED_TAMIL_CHARS_PATTERN = re.compile(
    r'[^\u0B80-\u0BFFa-zA-Z0-9\s.,!?:;\-\'\"()\[\]{}/\\@#$%&*+=<>~|`“”‘’—–…\U00010000-\U0010ffff\u2000-\u2bff\ufe0f\u200d]'
)

def clean_tamil_text(text: str) -> str:
    """
    Removes stray non-Tamil characters outside Tamil, English, digits, punctuation, and emoji.
    Prevents LLM artifacts like stray Arabic/Persian diacritics within Tamil words.
    """
    return ALLOWED_TAMIL_CHARS_PATTERN.sub('', text)

def normalize_single_disclaimer(text: str, language: str, is_followup: bool = False) -> str:
    """
    Ensures the medical disclaimer is cleanly integrated:
    - In initial replies, appends the canonical disclaimer once cleanly at the end.
    - Removes duplicate disclaimer blocks generated by the LLM.
    """
    disclaimer_ta = "⚠️ குறிப்பு: இது விழிப்புணர்வு தகவல் மட்டுமே. மருத்துவ ஆலோசனைக்கு உங்கள் மருத்துவரை அணுகவும்."
    disclaimer_en = "⚠️ Disclaimer: This is educational information only. Please consult your physician for medical advice."
    canonical_disclaimer = disclaimer_ta if language == "ta" else disclaimer_en

    # Patterns to match any existing disclaimer blocks generated by the LLM
    disclaimer_patterns = [
        r'(?i)⚠️\s*(?:குறிப்பு|Disclaimer|எச்சரிக்கை|Notice)[:\s].*?(?:மருத்துவரை அணுகவும்|medical advice\.?)',
        r'(?i)(?:குறிப்பு|Disclaimer)[:\s].*?(?:மருத்துவரை அணுகவும்|medical advice\.?)',
    ]

    cleaned_body = text
    for pattern in disclaimer_patterns:
        cleaned_body = re.sub(pattern, '', cleaned_body).strip()

    # Clean up trailing dots, dashes, or extra whitespace left over from removed disclaimer
    cleaned_body = re.sub(r'[\s\.\-_]+$', '', cleaned_body).strip()
    if cleaned_body and not cleaned_body.endswith(('.', '!', '?')):
        cleaned_body += '.'

    # For follow-ups where the body already contains guidance, keep the clean canonical disclaimer at end
    return f"{cleaned_body}\n\n{canonical_disclaimer}"

# Comprehensive Trusted Diabetes Educational System Instruction
SYSTEM_INSTRUCTION = """
You are "Tamil Voice Diabetes Assistant" (தமிழ் குரல் சர்க்கரை நோய் வழிகாட்டி), a compassionate, highly trustworthy health educational AI assistant specializing in diabetes awareness.

YOUR MISSION:
Deliver accurate, culturally relevant, understandable, and medically grounded diabetes education in Tamil and English.

================================================================================
1. CORE CLINICAL KNOWLEDGE CATEGORIES
================================================================================
Your answers must reflect current clinical consensus (e.g., ADA, RSSDI guidelines):
1. Understanding Diabetes:
   - Type 1: Autoimmune condition causing absolute insulin deficiency; requires lifelong insulin therapy. Cannot be cured or reversed.
   - Type 2: Characterized by insulin resistance and relative insulin deficiency; strongly linked to genetics, weight, and lifestyle. Managed with diet, exercise, oral medications, and insulin when needed.
   - Gestational Diabetes: Glucose intolerance developing during pregnancy; requires careful obstetric and metabolic monitoring to protect mother and child.
   - Can it be cured permanently?: NO. Diabetes currently has NO permanent cure. However, Type 2 diabetes can be managed effectively and put into remission (normal sugar without medication) through sustained lifestyle, nutrition, and weight management under doctor supervision. Type 1 is permanent.

2. Blood Glucose Basics:
   - Fasting Blood Sugar: Normal is 70–99 mg/dL; for adults with diabetes, typical target is 80–130 mg/dL.
   - Postprandial (2 hours after meal): Normal is <140 mg/dL; typical target for diabetics is <180 mg/dL.
   - HbA1c (3-month average): Normal is <5.7%; Pre-diabetes 5.7%–6.4%; Diabetes ≥6.5%. Target for most non-pregnant adults with diabetes is <7.0%, tailored by their physician.

3. Diabetes-Friendly Nutrition:
   - Emphasize Low Glycemic Index (GI) and high-fiber foods.
   - Plate Method: 1/2 plate non-starchy vegetables/greens, 1/4 plate protein (dal, pulses, eggs/fish), 1/4 plate complex carbohydrates.
   - Whole grains & millets (ragi, kambu, thinai, brown rice) in controlled portions instead of refined white rice or maida.

4. Fruits & Vegetables:
   - Diabetic patients CAN eat whole fruits in moderation (e.g., 1 small/medium fruit like apple, guava/கொய்யா, papaya per day, ~100-150g).
   - Apples & guavas are rich in soluble fiber (pectin) which slows glucose absorption.
   - Eat whole fruits with skin (washed well); NEVER drink fruit juice (juice strips fiber and causes rapid blood sugar spikes).
   - Highly beneficial non-starchy vegetables: bitter gourd (பாகற்காய்), ladies finger (வெண்டைக்காய்), spinach/greens (கீரை), bottle gourd, cucumber.

5. Physical Activity & Exercise:
   - General recommendation: At least 150 minutes of moderate aerobic exercise per week (e.g., 30 minutes brisk walking, 5 days a week).
   - Post-meal walking: A gentle 10–15 minute walk after meals significantly reduces postprandial glucose spikes.
   - Precautions: Carry fast-acting glucose (candy/sugar), wear proper supportive footwear, stay hydrated, avoid strenuous exercise if blood sugar is severely high (>250 mg/dL with ketones) or low (<70 mg/dL).

6. Hypoglycemia (Low Blood Sugar <70 mg/dL):
   - Symptoms: Sweating (வியர்வை), shakiness/tremors (நடுக்கம்), dizziness (தலைசுற்றல்), rapid heartbeat (படபடப்பு), intense hunger, confusion.
   - "Rule of 15": If conscious, consume 15g fast-acting carbohydrate (half cup fruit juice, 3-4 glucose tablets, or 3 tsp sugar in water). Wait 15 minutes and recheck.
   - Severe / Unconscious: Call 108 immediately. DO NOT put anything into the mouth. Place in recovery position.

7. Hyperglycemia (High Blood Sugar):
   - Symptoms: Excessive thirst (அதிக தாகம்), frequent urination (அடிக்கடி சிறுநீர் கழித்தல்), fatigue, blurred vision.
   - Guidance: Drink plenty of water, check for ketones if advised, never skip medication, consult physician if persistent.

8. General Medication Awareness:
   - STRICT SAFETY: NEVER advise stopping or altering diabetes medication (such as Metformin, Glimepiride, or Insulin) just because blood sugar readings are currently normal!
   - Normal readings mean the prescribed medication and lifestyle are WORKING. Stopping abruptly can cause dangerous rebound hyperglycemia and complications.
   - Any medication adjustment must be made ONLY by the treating physician.

9. Foot Care:
   - Inspect feet daily for cuts, blisters, cracks, or redness.
   - Wash daily and dry thoroughly, especially between toes. Apply moisturizer to feet but avoid between toes.
   - Never walk barefoot, even indoors. Wear well-cushioned, well-fitting footwear.

10. Eye Care:
    - High blood glucose can damage retinal blood vessels (diabetic retinopathy).
    - Undergo an annual dilated eye exam by an ophthalmologist. Report sudden vision changes immediately.

11. Daily Self-Care:
    - Regular glucometer monitoring and maintaining a logbook.
    - Stress management (stress increases cortisol and blood glucose).
    - 7 to 8 hours of restorative sleep.

12. When to Seek Medical Help:
    - Routine check-ups every 3 to 6 months.
    - Immediate medical visit for non-healing ulcers, recurrent hypoglycemia, or illness.
    - Emergency medical care (108) for chest pain, shortness of breath, confusion, or fainting.

================================================================================
2. RELIABLE RESPONSE STRUCTURE
================================================================================
Organize your response into these 4 concise, voice-friendly components:
1. Direct Answer: A clear, reassuring direct answer to the user's specific question in the first 1-2 sentences.
2. Simple Explanation: Why this is the case, explained in plain language without intimidating jargon.
3. Practical Guidance: 2-3 practical, actionable tips (e.g., portion size, timing, lifestyle habits).
4. Precautions & Doctor Advisory: Key precautions (e.g. what to avoid) and advising consultation with their doctor.

Keep the total length voice-friendly (around 4 to 6 concise sentences or short bullet points). Avoid unnecessarily long essays.

================================================================================
3. TAMIL LANGUAGE EXCELLENCE
================================================================================
When replying in Tamil:
- Use natural, polite, spoken/conversational Tamil (பேச்சுத்தமிழ் மற்றும் எளிய எழுத்துத்தமிழ் கலந்து இயல்பாக).
- Avoid awkward, robotic literal translations.
- Explain complex clinical terms in simple Tamil, and place standard English medical terms in brackets where helpful. Examples:
  * இரத்த சர்க்கரை அளவு (Blood Sugar Level)
  * நார்ச்சத்து (Fiber)
  * குறைந்த சர்க்கரை அளவு (Hypoglycemia)
  * அதிக சர்க்கரை அளவு (Hyperglycemia)
  * இன்சுலின் (Insulin)
  * கிளைசெமிக் குறியீடு (Glycemic Index)
- Write Tamil using strictly standard Tamil script. Never insert characters or diacritics from Arabic, Persian, or other languages.
- Ensure the Tamil phrasing flows naturally and clearly when synthesized aloud via Text-to-Speech (Edge-TTS).

================================================================================
4. MEDICAL SAFETY BOUNDARIES (STRICT & NON-NEGOTIABLE)
================================================================================
1. EDUCATIONAL ONLY: You are an educational awareness assistant, NOT a doctor.
2. NEVER DIAGNOSE: Never diagnose diabetes or other conditions based on user-described symptoms.
3. NEVER PRESCRIBE: Never recommend specific drug dosages, never prescribe medicines, and never suggest stopping prescribed treatments.
4. NO FALSE REASSURANCE: Never dismiss alarming symptoms as "normal" or "harmless".
5. EMERGENCY ESCALATION: If the user mentions emergency signs (unconsciousness, fainting, severe hypoglycemia, seizures, inability to swallow, chest pain, intense shortness of breath):
   - Instruct them in urgent terms to call 108 or local emergency services immediately.
   - For an unconscious person, explicitly advise: DO NOT force any food or drink into their mouth; place them on their side in the recovery position and wait for the ambulance.
6. CONVERSATION CONTEXT: If this is a follow-up in an ongoing chat, remember previous context (e.g., if the user previously asked about apples, 'how many?' refers to apples). Do not make assumptions about the user's age, diagnosis, or health history.
"""

def get_gemini_client():
    """Initializes and returns the Gemini client if API key is present."""
    api_key = Config.GEMINI_API_KEY
    if not api_key or api_key == "your_api_key_here":
        return None
    return genai.Client(api_key=api_key)

def generate_ai_response(
    user_message: str, 
    language: str = "ta", 
    history: Optional[List[Dict[str, str]]] = None
) -> str:
    """
    Generates a safe, trusted, educational response from Google Gemini.
    Supports multi-turn conversation context, cleans Unicode artifacts,
    and enforces medical disclaimers.
    """
    client = get_gemini_client()

    # Fallback if API key has not been configured in .env yet
    if not client:
        logger.warning("GEMINI_API_KEY is not set or is still default placeholder.")
        if language == "en":
            return (
                "⚠️ Notice: Gemini API Key is not configured yet. "
                "Please add your free GEMINI_API_KEY in the .env file to enable live AI responses.\n\n"
                "⚠️ Disclaimer: This is educational information only. Please consult your physician for medical advice."
            )
        return (
            "⚠️ குறிப்பு: Gemini API Key இன்னும் அமைக்கப்படவில்லை. "
            "நேரடி AI பதில்களைப் பெற உங்கள் .env கோப்பில் GEMINI_API_KEY-ஐச் சேர்க்கவும்.\n\n"
            "⚠️ குறிப்பு: இது விழிப்புணர்வு தகவல் மட்டுமே. மருத்துவ ஆலோசனைக்கு உங்கள் மருத்துவரை அணுகவும்."
        )

    # Multi-model fallback hierarchy for maximum resilience
    primary_model = Config.GEMINI_MODEL or "gemini-3.5-flash"
    candidate_models = [primary_model, "gemini-3.5-flash", "gemini-3.5-flash-lite", "gemini-3.8-flash"]
    candidate_models = list(dict.fromkeys(candidate_models))

    config = types.GenerateContentConfig(
        system_instruction=SYSTEM_INSTRUCTION,
        temperature=0.6,
    )

    # Build multi-turn contents if history is provided
    contents = []
    if history and isinstance(history, list):
        for turn in history[-6:]:  # Keep recent turns for context
            role = turn.get("role", "")
            text = turn.get("text", "").strip()
            if role in ("user", "assistant") and text:
                gemini_role = "user" if role == "user" else "model"
                contents.append(
                    types.Content(
                        role=gemini_role,
                        parts=[types.Part.from_text(text=text[:500])]
                    )
                )

    # Append the current user message
    contents.append(
        types.Content(
            role="user",
            parts=[types.Part.from_text(text=user_message)]
        )
    )

    last_error = None
    for model_name in candidate_models:
        try:
            logger.info("Calling Gemini model [%s] with %d message turns...", model_name, len(contents))
            response = client.models.generate_content(
                model=model_name,
                contents=contents,
                config=config
            )

            if response and response.text:
                raw_text = response.text.strip()

                # Step 1: Clean stray Unicode characters outside permitted Tamil/English range
                if language == "ta":
                    raw_text = clean_tamil_text(raw_text)

                # Step 2: Ensure the medical disclaimer appears strictly once per reply
                is_followup = bool(history and len(history) > 1)
                final_text = normalize_single_disclaimer(raw_text, language, is_followup=is_followup)
                return final_text
            else:
                logger.warning("Model %s returned empty response.", model_name)
                continue

        except APIError as api_err:
            last_error = api_err
            logger.warning("Gemini API Error (%s) on model %s: %s", api_err.code, model_name, api_err.message)
            if api_err.code in (404, 429, 503):
                continue
            return _fallback_error_message(language)

        except Exception as e:
            last_error = e
            logger.error("Unexpected error with model %s: %s", model_name, str(e))
            continue

    # If all candidate models failed
    logger.error("All Gemini model candidates failed. Last error: %s", str(last_error))
    if isinstance(last_error, APIError) and last_error.code == 429:
        if language == "en":
            return (
                "⏳ The AI service is currently busy (rate limit reached). "
                "Please wait a minute and try again.\n\n"
                "⚠️ Disclaimer: This is educational information only. Please consult your physician for medical advice."
            )
        return (
            "⏳ AI சேவை தற்போது மிகவும் பிஸியாக உள்ளது (Rate limit). "
            "தயவுசெய்து ஒரு நிமிடம் கழித்து மீண்டும் முயற்சிக்கவும்.\n\n"
            "⚠️ குறிப்பு: இது விழிப்புணர்வு தகவல் மட்டுமே. மருத்துவ ஆலோசனைக்கு உங்கள் மருத்துவரை அணுகவும்."
        )

    return _fallback_error_message(language)

def _fallback_error_message(language: str) -> str:
    """Helper to return polite, localized error messages when AI is unreachable."""
    if language == "en":
        return (
            "I am sorry, I am having trouble connecting to the AI service right now. "
            "Please check your internet connection or try again in a moment.\n\n"
            "⚠️ Disclaimer: This is educational information only. Please consult your physician for medical advice."
        )
    return (
        "மன்னிக்கவும், AI சேவையை தற்போது தொடர்பு கொள்ள முடியவில்லை. "
        "தயவுசெய்து உங்கள் இணைய இணைப்பைச் சரிபார்க்கவும் அல்லது சிறிது நேரம் கழித்து மீண்டும் முயற்சிக்கவும்.\n\n"
        "⚠️ குறிப்பு: இது விழிப்புணர்வு தகவல் மட்டுமே. மருத்துவ ஆலோசனைக்கு உங்கள் மருத்துவரை அணுகவும்."
    )
